(function(){var h=true,l=null,o=false,r=this,aa=function(a,b,c){a=a.split(".");c=c||r;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:c[d]={}},ba=function(a){return a.call.apply(a.bind,arguments)},ca=function(a,b){var c=b||r;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,d);return a.apply(c,f)}}else return function(){return a.apply(c,
arguments)}},s=function(){s=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ba:ca;return s.apply(l,arguments)};var t=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var u=function(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0};var v=function(a,b){this.width=a;this.height=b};v.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var x,y,z,A,E,da=function(){return r.navigator?r.navigator.userAgent:l};E=A=z=y=x=o;var F;if(F=da()){var ea=r.navigator;x=F.indexOf("Opera")==0;y=!x&&F.indexOf("MSIE")!=-1;A=(z=!x&&F.indexOf("WebKit")!=-1)&&F.indexOf("Mobile")!=-1;E=!x&&!z&&ea.product=="Gecko"}var G=x,H=y,fa=E,I=z,ga=A,ha;
a:{var J="",K;if(G&&r.opera){var ia=r.opera.version;J=typeof ia=="function"?ia():ia}else{if(fa)K=/rv\:([^\);]+)(\)|;)/;else if(H)K=/MSIE\s+([^\);]+)(\)|;)/;else if(I)K=/WebKit\/(\S+)/;if(K){var ka=K.exec(da());J=ka?ka[1]:""}}if(H){var la,ma=r.document;la=ma?ma.documentMode:undefined;if(la>parseFloat(J)){ha=String(la);break a}}ha=J}
var na=ha,oa={},L=function(a){var b;if(!(b=oa[a])){b=0;for(var c=String(na).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,d.length),e=0;b==0&&e<f;e++){var g=c[e]||"",p=d[e]||"",i=RegExp("(\\d*)(\\D*)","g"),q=RegExp("(\\d*)(\\D*)","g");do{var k=i.exec(g)||["","",""],j=q.exec(p)||["","",""];if(k[0].length==0&&j[0].length==0)break;b=t(k[1].length==0?0:parseInt(k[1],10),j[1].length==0?0:parseInt(j[1],10))||t(k[2].length==
0,j[2].length==0)||t(k[2],j[2])}while(b==0)}b=oa[a]=b>=0}return b};var pa;!H||L("9");H&&L("9");var ra=function(a){return a?new qa(M(a)):pa||(pa=new qa)},sa=function(a){a=!I&&a.compatMode=="CSS1Compat"?a.documentElement:a.body;return new u(a.scrollLeft,a.scrollTop)},M=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},qa=function(a){this.c=a||r.document||document};var N=document,O=window;function P(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function ta(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}
var ua=function(a,b){var c=b||O;if(a&&c.top!=c)c=c.top;try{var d;if(c.document&&!c.document.body)d=new v(-1,-1);else{c=c||window;var f=c.document;if(I&&!L("500")&&!ga){if(typeof c.innerHeight=="undefined")c=window;var e=c.innerHeight,g=c.document.documentElement.scrollHeight;if(c==c.top)if(g<e)e-=15;d=new v(c.innerWidth,e)}else{var p=f.compatMode=="CSS1Compat";if(G&&!L("9.50"))p=o;var i=p?f.documentElement:f.body;d=new v(i.clientWidth,i.clientHeight)}}return d}catch(q){return new v(-12245933,-12245933)}},
va=function(a){try{return!!a.document}catch(b){return o}};aa("google_protectAndRun",function(a,b,c){a=s(b,r,a);b=window.onerror;window.onerror=a;try{c()}catch(d){c=d.toString();var f="";if(d.fileName)f=d.fileName;var e=-1;if(d.lineNumber)e=d.lineNumber;if(!a(c,f,e))throw d;}window.onerror=b},void 0);
aa("google_handleError",function(a,b,c,d){if(Math.random()<0.01){a=["http://","pagead2.googlesyndication.com","/pagead/gen_204","?id=jserror","&jscb=",0,"&jscd=",0,"&context=",P(a),"&msg=",P(b),"&file=",P(c),"&line=",P(d.toString()),"&url=",P(N.URL.substring(0,512)),"&ref=",P(N.referrer.substring(0,512))];a.push(["&client=",P(O.google_ad_client),"&format=",P(O.google_ad_format),"&slotname=",P(O.google_ad_slot),"&output=",P(O.google_ad_output),"&ad_type=",P(O.google_ad_type)].join(""));ta(O,a.join(""))}return h},
void 0);var wa=!!window.google_async_iframe_id,Q=wa&&window.parent||window,R=function(){if(wa&&!va(Q)){for(var a="."+N.domain;a.split(".").length>2&&!va(Q);){N.domain=a=a.substr(a.indexOf(".")+1);Q=window.parent}va(Q)||(Q=window)}return Q};var T=function(a,b){var c;a:{c=M(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,l)){c=c[b]||c.getPropertyValue(b);break a}c=""}return c||(a.currentStyle?a.currentStyle[b]:l)||a.style[b]},xa=function(a){var b=a.getBoundingClientRect();if(H){a=a.ownerDocument;b.left-=a.documentElement.clientLeft+a.body.clientLeft;b.top-=a.documentElement.clientTop+a.body.clientTop}return b},ya=function(a){if(H)return a.offsetParent;var b=M(a),c=T(a,"position"),d=c=="fixed"||
c=="absolute";for(a=a.parentNode;a&&a!=b;a=a.parentNode){c=T(a,"position");d=d&&c=="static"&&a!=b.documentElement&&a!=b.body;if(!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c=="fixed"||c=="absolute"))return a}return l},Ba=function(a){var b,c=M(a),d=T(a,"position"),f=fa&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),e=new u(0,0),g;b=c?c.nodeType==9?c:M(c):document;if(g=H)g=ra(b).c.compatMode!="CSS1Compat";g=g?b.body:
b.documentElement;if(a==g)return e;if(a.getBoundingClientRect){b=xa(a);a=ra(c);a=sa(a.c);e.x=b.left+a.x;e.y=b.top+a.y}else if(c.getBoxObjectFor&&!f){b=c.getBoxObjectFor(a);a=c.getBoxObjectFor(g);e.x=b.screenX-a.screenX;e.y=b.screenY-a.screenY}else{b=a;do{e.x+=b.offsetLeft;e.y+=b.offsetTop;if(b!=a){e.x+=b.clientLeft||0;e.y+=b.clientTop||0}if(I&&T(b,"position")=="fixed"){e.x+=c.body.scrollLeft;e.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(G||I&&d=="absolute")e.y-=c.body.offsetTop;for(b=
a;(b=ya(b))&&b!=c.body&&b!=g;){e.x-=b.scrollLeft;if(!G||b.tagName!="TR")e.y-=b.scrollTop}}return e};var U,Ja=function(){try{var a=R(),b=a.document,c=V();Ca=c;if(Da()){Ea=U.numBlocks();var d=[];Fa=0;U.findBlocks(function(i,q){Fa++;var k=i.getBoundingClientRect(),j={x:0,y:0};try{var B=window.top,C=new u(0,0),m=M(i)?M(i).parentWindow||M(i).defaultView:window,D=i;do{var S;if(m==B)S=Ba(D);else{var n=D,w=new u;if(n.nodeType==1)if(n.getBoundingClientRect){var za=xa(n);w.x=za.left;w.y=za.top}else{var ja,Pa=ra(n);ja=sa(Pa.c);var Aa=Ba(n);w.x=Aa.x-ja.x;w.y=Aa.y-ja.y}else{w.x=n.clientX;w.y=n.clientY}S=w}n=
S;C.x+=n.x;C.y+=n.y}while(m&&m!=B&&(D=m.frameElement)&&(m=m.parent));j=C;d.push(new Ga(new W(Math.round(j.y),Math.round(j.x),Math.round(k.bottom-k.top+j.y),Math.round(k.right-k.left+j.x)),q,c))}catch(Ua){d.push(new Ga(Ha,q,c))}});X=d;var f=U.getOsdMode();if(f==1)Y("p");else{(f=f==0)&&Z();var e=function(){Y("f")},g=function(){Y("u")};if(b.attachEvent){b.attachEvent("onfocusout",e);a.attachEvent("onunload",g);f&&a.attachEvent("onscroll",Z)}else{a.addEventListener("blur",e,h);a.addEventListener("unload",
g,o);f&&a.addEventListener("scroll",Z,o)}window.setTimeout(function(){Y("t")},36E5)}Ia=V()-c}else Y("c")}catch(p){X=[];Y("x")}},Z=function(){if(!Ka){var a=ua(h);if(!(-1==a.width||-1==a.height||-12245933==a.width||-12245933==a.height)){var b=l;try{b=sa(document)}catch(c){return}a=new W(b.y,b.x,b.y+a.height,b.x+a.width);b=X;for(var d=V(),f=0;f<b.length;f++)b[f].update(d,a);La+=V()-d;Ma++}}},Y=function(a){var b=R(),c=b.document;if(!Ka){var d=["http://pagead2.googlesyndication.com/pagead/gen_204?id=osd"];
try{var f=Ca>0?V()-Ca:-1,e=X;if(e.length>0){Z();for(c=0;c<e.length;c++)if(e[c].f>0){var g=e[c],p=g.i,i=["p:",p.top,p.left,p.bottom,p.right];i.push("tos:",g.a.join(","));i.push("zoom:",g.zoom.join(","));g.b>=0&&i.push("tfs:",g.b,"tls:",g.j);i.push("fp:",g.k);var q=P(i.join(","));d.push("ad"+(e[c].f-1)+"="+q);e[c].d>0&&d.push("adk"+e[c].d+"="+q)}var k,j=ua(h);d.push("bs="+j.width+","+j.height);var B,C=R(),m=C.document;B=!C.scrollY&&m.compatMode!="CSS1Compat"?new W(0,0,m.body.scrollHeight,m.body.scrollWidth):
new W(0,0,m.body.offsetHeight,m.body.offsetWidth);d.push("ps="+B.right+","+B.bottom);d.push("fp="+P(Na(Oa,e[0].url)))}else{d.push("url="+P(b.location.href));c.referrer&&d.push("referrer="+P(c.referrer));if(U){d.push("correlator="+U.getCorrelator());d.push("eid="+U.getEid())}}d.push("tt="+f);d.push("deb="+P([1,Ea,Fa,La,Ma,Ia].join("-")));d.push("r="+a);if(b.top!=b){d.push("iframe_loc="+P(b.location.href));k=o;var D=ua(k);d.push("is="+D.width+","+D.height)}}catch(S){d.push("error")}try{ta(window,d.join("&"))}catch(n){}Ka=
h}},Qa=/[&\?](?:correlator|slotname|dt|format)=[^&]+/g,Oa=/[&\?](?:client|correlator|url|ifk|eid)=[^&]+/g,Na=function(a,b){var c=b.match(a);return c?c.join(""):""},X=[],Ka=o,Ra=(new Date).getTime(),Ca=-1,V=function(){return(new Date).getTime()-Ra},Ea=0,Fa=0,La=0,Ma=0,Ia=0,Da=function(){var a=R(),b=a.document;if(!b.body||!b.body.getBoundingClientRect||typeof Goog_AdSense_getAdAdapterInstance!="function")return o;U=Goog_AdSense_getAdAdapterInstance();if(typeof a.scrollY=="undefined")if(!b.compatMode)return o;
return h},Ga=function(a,b,c){this.i=a;this.e=(a.bottom-a.top)*(a.right-a.left);this.j=this.b=-1;this.a=[0,0,0,0,0];this.zoom=[0,0,0,0,0];this.k=Na(Qa,b);this.h=o;this.g=c;this.url=b;a=(a=b.match(/[&\?](?:ifi)=([0-9]+)/))&&a.length==2?parseInt(a[1],10):0;this.f=a;b=(b=b.match(/[&\?](?:adk)=([0-9]+)/))&&b.length==2?parseInt(b[1],10):0;this.d=b};
Ga.prototype.update=function(a,b){var c=this.i,d=a-this.g||1;this.g=a;var f=Math.max(c.top,b.top),e=Math.min(c.bottom,b.bottom);this.h=o;if(f<=e){var g=Math.max(c.left,b.left);c=Math.min(c.right,b.right);if(g<=c){f=(e-f)*(c-g)/this.e;if(f>=1)this.a[0]+=d;else if(f>=0.75)this.a[1]+=d;else if(f>=0.5)this.a[2]+=d;else if(f>=0.25)this.a[3]+=d;else this.a[4]+=d;if(this.b<0)this.b=a;this.j=a;this.h=h;if(f>=0.5){f=100*this.e/((b.bottom-b.top)*(b.right-b.left));if(f>=20)this.zoom[0]+=d;else if(f>=10)this.zoom[1]+=
d;else if(f>=5)this.zoom[2]+=d;else if(f>=2.5)this.zoom[3]+=d;else this.zoom[4]+=d}}}};var W=function(a,b,c,d){this.top=a;this.bottom=c;this.left=b;this.right=d},Ha=new W(0,0,0,0);var Sa=R();if(Sa.document.readyState=="complete"||Sa.google_onload_fired)Ja();else{var $=R(),Ta=function(){window.setTimeout(Ja,1100)};if($.attachEvent)$.attachEvent("onload",Ta);else $.addEventListener&&$.addEventListener("load",Ta,o)};})();
